### ISSUE TITLE
您好，问一下，现在马蜂窝那个rebots最后一段，是禁止所有个人爬虫爬取信息吗？

### ISSUE THREAD

**Issue by Sunyihao** [Kevin-Cherish/NeteaseCloudMusic#1]
我因为需要收集一些简单的旅游信息作为毕设的信息备用，突然发现现在不可以了。

**Comment by dli98** [comment]
User-agent: *
Disallow: /
Disallow: /poi/detail.php
禁止所有人爬取detail.php。但只是一个君子协议。如果只是用在毕设的话，我觉得问题不大。
